### ISSUE TITLE
get_frame_count not implemented in 'webgl' viewer

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#191]
I'm getting a `NotImplementedError()` when I call the `view` method on a `Molecule` object. More specifically, I'm running:
```python
from htmd import *
htmd.config(viewer='webgl')
%pylab inline
mol = Molecule('ntl9_structure.pdb')
mol.read('ntl9_trajectory.xtc')
mol.filter('protein')
mol.view()
```
The full Traceback is:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-16c4022e2101> in <module>()
      2 mol.read('ntl9_trajectory.xtc')
      3 mol.filter('protein')
----> 4 mol.view()

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in view(self, sel, style, color, guessBonds, viewer, hold, name, viewerhandle, gui)
    950             self._viewVMD(psf, xtc, viewerhandle, name, guessBonds)
    951         elif viewer.lower() == 'ngl' or viewer.lower() == 'webgl':
--> 952             return self._viewNGL(gui=gui)
    953         else:
    954             raise ValueError('Unknown viewer.')

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in _viewNGL(self, gui)
   1021 
   1022         traj = HTMDTrajectory(self)
-> 1023         w = nglview.NGLWidget(traj, gui=gui)
   1024 
   1025         self._tempreps.append(self.reps)

/Users/je714/anaconda3/lib/python3.5/site-packages/nglview/__init__.py in __init__(self, structure, trajectory, representations, **kwargs)
    134             self.trajectory = structure
    135         if hasattr( self, "trajectory" ) and hasattr( self.trajectory, "get_frame_count" ):
--> 136             self.count = self.trajectory.get_frame_count()
    137         if representations:
    138             self.representations = representations

/Users/je714/anaconda3/lib/python3.5/site-packages/nglview/__init__.py in get_frame_count(self)
     66 
     67     def get_frame_count( self ):
---> 68         raise NotImplementedError()
     69 
     70 

NotImplementedError: 
```
If I change to the `VMD` viewer this works fine.
My conda packages are the following:
```
htmd                      1.5.4                    py35_0    acellera
htmd-data                 0.0.37                   py35_0    acellera
htmd-pdb2pqr              2.1.2a8                  py35_0    acellera
htmdbabel                 2.3.95                   py35_0    acellera
nglview                   0.0.5                         2    acellera
```

Any ideas on how to fix this? Am I missing any library?

**Comment by j3mdamas** [comment]
You need to update that nglview.
```
conda update nglview -c acellera
```
Let me know if it solves it.

**Comment by jeiros** [comment]
```
$ conda update nglview -c acellera
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /Users/je714/anaconda3:
#
nglview                   0.0.5                         2    acellera
```
Does it think it's on the last version?

**Comment by j3mdamas** [comment]
probably. do: `conda update nglview -c acellera --force` If it does not work, do `conda remove nglview` and `conda install nglview -c acellera -y`

**Comment by stefdoerr** [comment]
I have the impression this has to do with python versions. I saw this
before when for some reason the 2 version is installed instead of the 3.5.
Might need uninstall as Joao said

**Comment by jeiros** [comment]
I tried
```
$ conda update nglview -c acellera --force
Fetching package metadata .............
Solving package specifications: ..........

Package plan for installation in environment /Users/je714/anaconda3:

The following NEW packages will be INSTALLED:

    nglview: 0.0.5-2 acellera

Proceed ([y]/n)? y

Pruning extracted packages from the cache ...
[      COMPLETE      ]|######################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|######################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
```
But there's still an error, with a different Traceback:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-16c4022e2101> in <module>()
      2 mol.read('ntl9_trajectory.xtc')
      3 mol.filter('protein')
----> 4 mol.view()

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in view(self, sel, style, color, guessBonds, viewer, hold, name, viewerhandle, gui)
    950             self._viewVMD(psf, xtc, viewerhandle, name, guessBonds)
    951         elif viewer.lower() == 'ngl' or viewer.lower() == 'webgl':
--> 952             return self._viewNGL(gui=gui)
    953         else:
    954             raise ValueError('Unknown viewer.')

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in _viewNGL(self, gui)
    993 
    994     def _viewNGL(self, gui=False):
--> 995         from nglview import Trajectory
    996         import nglview
    997 

ImportError: cannot import name 'Trajectory'
```

**Comment by j3mdamas** [comment]
Hi @jeiros. Try the remove/install pair.
The current version is:
```
nglview                   0.5.2                    py35_4    acellera
```

**Comment by stefdoerr** [comment]
I am starting to remember that @mj-harvey said something about deleting some conda configs. Matt???

**Comment by jeiros** [comment]
I tried it on a fresh environment
```
conda create -n htmd-workshop
source activate htmd-workshop
conda install htmd
conda install jupyter
```
And I'm still getting the `ImportError`

My `.condarc` file is:
channels:
  - defaults
  - acellera
  - omnia
  - r
```
And the output of `conda list | grep acellera` is:
```
acecloud-client           1.0.24                   py35_1    acellera
acemd                     0.0.0                         0    acellera
ambermini                 15.0.4                        5    acellera
bhmm                      0.6.1               np111py35_0    acellera
dftd3                     3.2.0                         7    acellera
htmd                      1.5.4                    py35_0    acellera
htmd-data                 0.0.37                   py35_0    acellera
htmd-pdb2pqr              2.1.2a8                  py35_0    acellera
match                     0.0.2                         0    acellera
mdtraj                    1.7.2               np111py35_0    acellera
msmtools                  1.1.4               np111py35_0    acellera
nglview                   0.0.5                         2    acellera
openbabel                 2015.09                  py35_1    acellera
pcmsolver                 1.1.4                         0    acellera
pint                      0.7.2                    py35_0    acellera
progress_reporter         1.2                        py_1    acellera
propka                    3.1.6                    py35_0    acellera
psfgen                    1.6.9                         0    acellera
psi4                      0.0.0                         0    acellera
pyemma                    2.2.7               np111py35_0    acellera
thermotools               0.2.3               np111py35_0    acellera
vina                      1.1.101                       0    acellera
```

**Comment by j3mdamas** [comment]
Really weird. What does `conda install -c acellera nglview=0.5.2` give you?
If that does not fix it for you, I would consider a fresh conda installation :) that's something we do from time to time :P

**Comment by j3mdamas** [comment]
Oh wait, you're on OSX, right?

**Comment by jeiros** [comment]
```
$ conda install -c acellera nglview=0.5.2
Fetching package metadata .............
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels:
  - nglview 0.5.2*

You can search for packages on anaconda.org with

    anaconda search -t conda nglview

```

And looking for it:
```
$  anaconda search -t conda nglview
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     AmberMD/nglview           |    0.5.1 | conda           | linux-64, osx-64
                                          : An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
     AmberMD/nglview-dev       |  0.5.dev | conda           | linux-64, osx-64
                                          : An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
     acellera/nglview          |    0.5.2 | conda           | linux-64, osx-64
     bioconda/nglview          |    0.5.2 | conda           | linux-64, osx-64
                                          : An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
     hainm/nglview-dev         |  0.5.dev | conda           | linux-64
                                          : An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
     omnia/nglview             |      0.4 | conda           | None-None, linux-64, win-32, win-64, osx-64
                                          : IPython widget to interactively view molecular structures and trajectories.
Found 6 packages
```
Which is weird because it looks like it finds it?

**Comment by j3mdamas** [comment]
We don't have the latest nglview on OSX...

**Comment by jeiros** [comment]
Yeah I'm on OSX sorry forgot to mention that :(

**Comment by jeiros** [comment]
Oh ok that at least solves the mistery 😄

**Comment by j3mdamas** [comment]
@mj-harvey, can we have the new nglview on OSX?

**Comment by stefdoerr** [comment]
@mj-harvey you said that it's a platform independent build. Can you please release the one for OSX?

**Comment by stefdoerr** [comment]
@jeiros if you update nglview it should now pull the version of Alexander from Conda which should support OSX as well. Can you confirm it works?

**Comment by jeiros** [comment]
Hi, 

This still doesn't work from a fresh install with
```
conda create -n htmd-workshop -y
source activate htmd-workshop
conda install htmd jupyter -y
```
This gives the following environment:
```
name: htmd-workshop
channels: !!python/tuple
- defaults
- acellera
- omnia
- r
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- acellera::acecloud-client=1.0.24=py35_1
- acellera::acemd=0.0.0=0
- acellera::ambermini=15.0.4=5
- acellera::bhmm=0.6.1=np111py35_0
- acellera::dftd3=3.2.0=7
- acellera::htmd=1.5.4=py35_0
- acellera::htmd-data=0.0.37=py35_0
- acellera::htmd-pdb2pqr=2.1.2a8=py35_0
- acellera::match=0.0.2=0
- acellera::mdtraj=1.8.0=np111py35_0
- acellera::msmtools=1.1.4=np111py35_0
- acellera::nglview=0.6.1=py35_0
- acellera::openbabel=2015.09=py35_1
- acellera::pcmsolver=1.1.4=0
- acellera::pint=0.7.2=py35_0
- acellera::progress_reporter=1.2=py_1
- acellera::propka=3.1.6=py35_0
- acellera::psfgen=1.6.9=0
- acellera::psi4=0.0.0=0
- acellera::pyemma=2.2.7=np111py35_0
- acellera::thermotools=0.2.3=np111py35_0
- acellera::vina=1.1.101=0
- alabaster=0.7.9=py35_0
- anaconda-client=1.5.5=py35_0
- appnope=0.1.0=py35_0
- astroid=1.4.7=py35_0
- babel=2.3.4=py35_0
- boto3=1.4.1=py35_0
- botocore=1.4.79=py35_0
- clyent=1.2.2=py35_0
- cycler=0.10.0=py35_0
- cython=0.25.1=py35_0
- decorator=4.0.10=py35_0
- docutils=0.12=py35_2
- entrypoints=0.2.2=py35_0
- et_xmlfile=1.0.1=py35_0
- freetype=2.5.5=1
- funcsigs=0.4=py35_0
- hdf5=1.8.17=1
- icu=54.1=0
- imagesize=0.7.1=py35_0
- ipykernel=4.5.1=py35_0
- ipyparallel=5.2.0=py35_0
- ipython=5.1.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jdcal=1.3=py35_0
- jedi=0.9.0=py35_1
- jinja2=2.8=py35_1
- jmespath=0.9.0=py35_0
- joblib=0.9.4=py35_0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- lazy-object-proxy=1.2.1=py35_0
- libgcc=4.8.5=1
- libpng=1.6.22=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mistune=0.7.3=py35_1
- mkl=11.3.3=0
- mock=2.0.0=py35_0
- natsort=5.0.1=py35_0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- notebook=4.2.3=py35_0
- numexpr=2.6.1=np111py35_1
- numpy=1.11.2=py35_0
- openpyxl=2.4.0=py35_0
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- path.py=8.2.1=py35_0
- pbr=1.10.0=py35_0
- pep8=1.7.0=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_0
- prompt_toolkit=1.0.9=py35_0
- psutil=5.0.0=py35_0
- ptyprocess=0.5.1=py35_0
- pyflakes=1.3.0=py35_0
- pygments=2.1.3=py35_0
- pylint=1.5.4=py35_1
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- pytables=3.3.0=np111py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- python.app=1.2=py35_4
- pytz=2016.7=py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.0=0
- qtawesome=0.3.3=py35_0
- qtconsole=4.2.1=py35_1
- qtpy=1.1.2=py35_0
- readline=6.2=2
- requests=2.12.1=py35_0
- rope=0.9.4=py35_1
- s3transfer=0.1.9=py35_0
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.8=py35_0
- spyder=3.0.2=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- wrapt=1.10.8=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - pdb2pqr==2.1.2a1
  - progress-reporter==1.2
  - prompt-toolkit==1.0.9
  - rope-py3k==0.9.4.post1
  - tables==3.3.0
prefix: /Users/je714/anaconda3/envs/htmd-workshop
```
Trying to update nglview gives:
```
$ conda update nglview
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /Users/je714/anaconda3/envs/htmd-workshop:
#
nglview                   0.6.1                    py35_0    acellera
```
And the Error Traceback is:
```
2016-12-01 17:20:47,026 - htmd.molecule.molecule - INFO - Removed 17 atoms. 631 atoms remaining in the molecule.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-16c4022e2101> in <module>()
      2 mol.read('ntl9_trajectory.xtc')
      3 mol.filter('protein')
----> 4 mol.view()

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in view(self, sel, style, color, guessBonds, viewer, hold, name, viewerhandle, gui)
    950             self._viewVMD(psf, xtc, viewerhandle, name, guessBonds)
    951         elif viewer.lower() == 'ngl' or viewer.lower() == 'webgl':
--> 952             return self._viewNGL(gui=gui)
    953         else:
    954             raise ValueError('Unknown viewer.')

/Users/je714/anaconda3/lib/python3.5/site-packages/htmd/molecule/molecule.py in _viewNGL(self, gui)
    993 
    994     def _viewNGL(self, gui=False):
--> 995         from nglview import Trajectory
    996         import nglview
    997 

ImportError: cannot import name 'Trajectory'
```

**Comment by j3mdamas** [comment]
well, 0.6.1 is the latest, so no problems there...

**Comment by j3mdamas** [comment]
any clue, @stefdoerr?

**Comment by stefdoerr** [comment]
It's a different error now. The import I think is not needed there, however I don't get it why it would cause an error. Trajectory is an integral part of nglview unless they decided to hide it and I'm a version behind. I'll check it tomorrow.

**Comment by stefdoerr** [comment]
The error is fixed in the new htmd version. I tested it on an OSX machine here. If you can wait a bit we should have a release in the next few days. Otherwise you can pull the git version and put it in your `PYTHONPATH`.

By the way if after that there is no error but it simply doesn't show anything except an `X` try doing only once from commandline:
```
jupyter-nbextensions enable --py nglview
```
This should theoretically be done during nglview installation but it didn't work for me and I had to do it manually.

**Comment by jeiros** [comment]
I can wait 😄 Thanks for taking a look into this!

**Comment by stefdoerr** [comment]
I made an issue on this at nglview just in case: https://github.com/arose/nglview/issues/545

**Comment by hainm** [comment]
hi all,

we just created a bugfix for `nglview`, (`v0.6.2.1`). seems work fine for me.

`conda install -c bioconda nglview --force`

cc @arose

thanks @stefdoerr  and @j3mdamas to bring this issue to us.

**Comment by jeiros** [comment]
Hi, 

Just installed  with `conda install -c bioconda nglview --force` and then ran `jupyter nbextension enable nglview --user --py` as suggested after the installation.

I check that the correct version is installed after this:
```
$ conda list | grep nglview
nglview                   0.6.2.1                  py35_0    bioconda
```
But the `ImportError: cannot import name 'Trajectory'` is still persisting.

**Comment by stefdoerr** [comment]
@jeiros this will go away in the next htmd release as I mentioned above. You can wait for the next release (hopefully start of next week) or pull the github repo

**Comment by jeiros** [comment]
Ah my bad though @hainm was saying that end users could fix the bug installing the more recent version.

**Comment by hainm** [comment]
my apology. @stefdoerr opened an issue on `nglview` and we only fixed that. But the importing error is weird.

**Comment by j3mdamas** [comment]
@stefdoerr, can we close this?

**Comment by stefdoerr** [comment]
AFAIK it's resolved
